export const FAQ = [
    { q: "Apa itu HMTI UIN Antasari?", a: "HMTI UIN Antasari adalah organisasi mahasiswa TI di UIN Antasari Banjarmasin yang menjadi wadah kolaborasi dan pengembangan kapasitas mahasiswa." },
    { q: "HMTI itu singkatan dari apa?", a: "HMTI adalah singkatan dari Himpunan Mahasiswa Teknologi Informasi." },
    { q: "Kapan HMTI berdiri?", a: "HMTI lahir pada tahun 2025." },
    { q: "Sejak kapan perjalanan pembentukan HMTI dimulai?", a: "Narasi sejarah menyebut perjalanan panjang HMTI dimulai sejak tahun 2023 dan lahir resmi pada 2025." },
    { q: "Apa visi utama HMTI?", a: 'Visi yang ditonjolkan: "No One Left Behind." HMTI hadir untuk merangkul semua mahasiswa TI.' },
    { q: "Apa Visi Gerak Himpunan Kabinet Arnanta?", a: "Menjadikan sentra berhimpun mahasiswa TI sebagai dinamisator kolaborasi dan aksi transformatif yang berlandaskan nilai-nilai Islami." },
    { q: "Apa saja poros utama visi Kabinet Arnanta?", a: "Empat poros utama: Sentra Berhimpun, Dinamisator Kolaborasi, Aksi Transformatif, dan Nilai Islami." },
    { q: "Apa misi strategis Kabinet Arnanta?", a: "Misi strategis kabinet berfokus pada sentra kolaborasi dinamis, organisasi berintegritas, nilai Islami sebagai landasan, ekosistem pembelajaran kolaboratif, dan jejaring kemitraan strategis." },
    { q: "Tujuan umum HMTI dibangun untuk apa?", a: "HMTI dibangun sebagai jembatan profesional dan akademik untuk menyatukan potensi mahasiswa TI agar bertumbuh bersama." },
    { q: "Alamat kampus?", a: "UIN Antasari Banjarmasin, Jl. A. Yani KM 4.5, Banjarmasin, Kalimantan Selatan, Indonesia 70235." },
    { q: "Kontak email HMTI apa?", a: "Email kontak default yang digunakan di website adalah hmti@uinantasari.ac.id." },
    { q: "Apa Instagram resmi HMTI?", a: "Instagram default HMTI: https://www.instagram.com/hmit_uinantasari" },
    { q: "Apa akun X atau Twitter HMTI?", a: "Akun X/Twitter default HMTI: https://x.com/hmtiuinantasari" },
    { q: "Apa LinkedIn HMTI?", a: "LinkedIn default HMTI: https://linkedin.com/company/hmtiuinantasari" },
    { q: "Menu utama website HMTI apa saja?", a: "Menu utama di header: Sejarah Kami, Kabinet, Berita, Keuangan, dan Sertifikat Checker." },
    { q: "Halaman Sejarah Kami ada di mana?", a: "Halaman Sejarah Kami tersedia di route /sejarah-kami." },
    { q: "Halaman Kabinet ada di mana?", a: "Halaman Kabinet tersedia di route /kabinet." },
    { q: "Halaman Berita ada di mana?", a: "Halaman Berita tersedia di route /berita." },
    { q: "Halaman Keuangan ada di mana?", a: "Halaman Keuangan tersedia di route /keuangan." },
    { q: "Halaman Certificate Checker ada di mana?", a: "Halaman validasi sertifikat tersedia di route /certificate-checker." },
    { q: "Apa itu BPH di struktur kabinet?", a: "BPH adalah Badan Pengurus Harian." },
    { q: "Apa itu BDK?", a: "BDK adalah Branding Digital Kreatif, tim publikasi visual, dokumentasi, dan penguatan identitas media organisasi." },
    { q: "Apa itu HUKES?", a: "HUKES adalah Hubungan dan Kerjasama, tim relasi eksternal, komunikasi kelembagaan, dan kolaborasi lintas organisasi." },
    { q: "Apa itu KEMHAS?", a: "KEMHAS adalah Kemasyarakatan, tim pembinaan anggota, kaderisasi, serta aktivasi program mahasiswa internal." },
    { q: "Apa itu KEWISHAN?", a: "KEWISHAN adalah Kewirausahawan, tim pengembangan usaha, unit bisnis mahasiswa, dan inovasi program ekonomi kreatif." },
    { q: "Apa itu RISTEK?", a: "RISTEK adalah Riset dan Teknologi, tim pengembangan teknologi, kelas teknis, dan proyek berbasis riset mahasiswa." },
    { q: "Apa jobdesk utama BPH?", a: "Jobdesk utama BPH mencakup koordinasi internal, administrasi dan keuangan, pengembangan anggota, serta kolaborasi eksternal." },
    { q: "Apa jobdesk tim BDK?", a: "BDK menyusun konsep desain publikasi, mengelola dokumentasi foto/video kegiatan, dan menjaga konsistensi branding media sosial serta aset digital." },
    { q: "Apa jobdesk tim HUKES?", a: "HUKES membangun kemitraan eksternal, mengelola kanal informasi resmi untuk komunikasi publik, dan menyiapkan protokol hubungan kelembagaan." },
    { q: "Apa jobdesk tim KEMHAS?", a: "KEMHAS menyusun pola kaderisasi, mengelola pembinaan soft skill dan budaya organisasi, serta mengaktifkan partisipasi anggota." },
    { q: "Apa jobdesk tim KEWISHAN?", a: "KEWISHAN merancang program kewirausahaan, mengelola operasional unit usaha, dan mendorong inovasi ekonomi kreatif untuk pendanaan himpunan." },
    { q: "Apa jobdesk tim RISTEK?", a: "RISTEK menyusun kelas teknis dan mentoring, menginisiasi mini project dan riset terapan, serta mendokumentasikan output teknologi sebagai portofolio divisi." },
    { q: "Bagaimana cara validasi sertifikat?", a: "Buka halaman /certificate-checker, masukkan kode unik sertifikat, lalu klik Periksa." },
    { q: "Format kode sertifikat seperti apa?", a: "Format kode yang dicontohkan di website: HMIT-TI-(Nama kegiatan)-(kode)." },
    { q: "Kode sertifikat ditulis di bagian mana?", a: "Kode sertifikat tertulis di bagian atas sertifikat." },
    { q: "Kalau kode sertifikat tidak ditemukan bagaimana?", a: "Sistem menampilkan status tidak terdaftar dan meminta pengguna memastikan kode lalu mencoba lagi." },
    { q: "Kalau kode terdaftar tapi PDF belum ada bagaimana?", a: "Sistem menampilkan bahwa kode terdaftar, tetapi file PDF sertifikat belum tersedia di storage." },
    { q: "Apa yang muncul jika sertifikat valid?", a: "Jika valid, checker menampilkan badge Valid serta informasi kode, ID, tanggal, dan tombol View/Download PDF." },
    { q: "Apakah Certificate Checker bisa dibuka dengan parameter code di URL?", a: "Bisa. Halaman checker mendukung query parameter code untuk auto-check saat dibuka." },
    { q: "Apakah kode sertifikat otomatis dinormalisasi?", a: "Ya. Kode dibersihkan (trim), diubah uppercase, spasi dihapus, karakter tidak valid dibuang, dan tanda minus dirapikan." },
    { q: "Bucket default penyimpanan sertifikat apa?", a: "Bucket default sertifikat adalah 'certificates', kecuali diubah lewat NEXT_PUBLIC_CERTIFICATE_BUCKET." },
    { q: "Halaman health status ada di mana?", a: "Halaman status layanan tersedia di route /health." },
    { q: "Endpoint health API untuk monitoring apa?", a: "Endpoint JSON monitoring adalah /api/health." },
    { q: "Status code endpoint health bagaimana?", a: "Endpoint health memakai status 200 untuk operational/degraded dan 503 untuk kondisi down/outage." },
    { q: "Komponen apa saja yang dipantau di health check?", a: "Komponen yang dicek meliputi Web Service, Supabase, dan Gemini API." },
    { q: "Status layanan health check menggunakan label apa?", a: "Label status utama: Operational, Degraded, dan Major Outage." },
    { q: "Bagaimana cara masuk admin dashboard?", a: "Akses /login lalu login dengan email dan password akun admin Supabase. Setelah berhasil akan diarahkan ke /admin." },
    { q: "Apakah admin dashboard butuh autentikasi?", a: "Ya. Route admin memerlukan sesi login; jika belum login pengguna diarahkan ke halaman /login." },
    { q: "Menu cepat di dashboard admin apa saja?", a: "Quick actions admin mencakup Calendar Events, Manage News, Team Members, dan Settings." },
    { q: "Data utama yang dikelola sistem HMTI apa saja?", a: "Data utama meliputi kalender kegiatan, berita/kegiatan, anggota tim, sertifikat, dan pengaturan situs." },
    { q: "Halaman keuangan menampilkan apa?", a: "Halaman /keuangan menampilkan arsip laporan keuangan, overview kas, serta dokumen yang dapat difilter per tahun atau per kabinet." },
    { q: "Dokumen laporan keuangan HMTI bisa diunduh?", a: "Bisa. Di halaman keuangan tersedia tombol Download PDF untuk dokumen yang memiliki file." },
    { q: "Periode arsip laporan keuangan yang ditampilkan apa?", a: "Label periode arsip di halaman keuangan: Arsip laporan 2025 - 2026." },
    { q: "Laporan keuangan kabinet apa yang tersedia di arsip saat ini?", a: "Data arsip menampilkan laporan Kabinet Arnanta, termasuk dokumen tahun 2025 dan 2026." },
    { q: "Apa fungsi halaman berita HMTI?", a: "Halaman /berita menampilkan publikasi berita terbaru, mendukung pencarian, dan filter kategori." },
    { q: "Apakah website HMTI punya halaman khusus status layanan realtime?", a: "Ya. Tersedia halaman /health untuk melihat status layanan HMTI secara realtime." },
];
