-- Create SiteSettings table used by /admin/settings and public layout/footer data.
create table if not exists public."SiteSettings" (
    id bigint generated by default as identity primary key,
    site_name text not null default 'HMTI UIN Antasari',
    site_tagline text,
    contact_email text,
    contact_phone text,
    address text,
    facebook_url text,
    twitter_url text,
    instagram_url text,
    linkedin_url text,
    youtube_url text,
    about_text text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists site_settings_updated_at_idx
    on public."SiteSettings" (updated_at desc, id desc);

create or replace function public.set_site_settings_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_site_settings_set_updated_at on public."SiteSettings";
create trigger trg_site_settings_set_updated_at
before update on public."SiteSettings"
for each row
execute function public.set_site_settings_updated_at();

-- Seed one default row so the admin settings form has initial data.
insert into public."SiteSettings" (
    site_name,
    site_tagline,
    contact_email,
    contact_phone,
    address,
    facebook_url,
    twitter_url,
    instagram_url,
    linkedin_url,
    youtube_url,
    about_text
)
select
    'HMTI UIN Antasari',
    'Kabinet Arnanta',
    'hmti@uinantasari.ac.id',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'Website Resmi Himpunan Mahasiswa Teknologi Informasi (HMTI) UIN Antasari Banjarmasin.'
where not exists (
    select 1 from public."SiteSettings"
);
